name: LGNJetClassifier
channels:
    - conda-forge
    - pytorch
dependencies:
    - python
    - numpy
    - scipy
    - scikit-learn
    - h5py
    - colorlog
    - pytorch
    - matplotlib
    - time
    - seaborn
    - pip
